### ISSUE TITLE
ERROR scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by luobailian** [citiususc/SparkBWA#20]
16/07/25 15:45:17 INFO yarn.Client: Application report for application_1469432674658_0001 (state: ACCEPTED)
16/07/25 15:45:18 INFO yarn.Client: Application report for application_1469432674658_0001 (state: ACCEPTED)
16/07/25 15:45:19 INFO yarn.Client: Application report for application_1469432674658_0001 (state: ACCEPTED)
16/07/25 15:45:20 INFO cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster registered as NettyRpcEndpointRef(null)
16/07/25 15:45:20 INFO cluster.YarnClientSchedulerBackend: Add WebUI Filter. org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter, Map(PROXY_HOSTS -> master, PROXY_URI_BASES -> http://master:8088/proxy/application_1469432674658_0001), /proxy/application_1469432674658_0001
16/07/25 15:45:20 INFO ui.JettyUtils: Adding filter: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter
16/07/25 15:45:20 INFO yarn.Client: Application report for application_1469432674658_0001 (state: RUNNING)
16/07/25 15:45:20 INFO yarn.Client: 
     client token: N/A
     diagnostics: N/A
     ApplicationMaster host: 192.168.100.3
     ApplicationMaster RPC port: 0
     queue: default
     start time: 1469432715822
     final status: UNDEFINED
     tracking URL: http://master:8088/proxy/application_1469432674658_0001/
     user: root
16/07/25 15:45:20 INFO cluster.YarnClientSchedulerBackend: Application application_1469432674658_0001 has started running.
16/07/25 15:45:20 INFO util.Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 52523.
16/07/25 15:45:20 INFO netty.NettyBlockTransferService: Server created on 52523
16/07/25 15:45:20 INFO storage.BlockManagerMaster: Trying to register BlockManager
16/07/25 15:45:20 INFO storage.BlockManagerMasterEndpoint: Registering block manager 192.168.100.6:52523 with 853.1 MB RAM, BlockManagerId(driver, 192.168.100.6, 52523)
16/07/25 15:45:20 INFO storage.BlockManagerMaster: Registered BlockManager
16/07/25 15:45:21 INFO scheduler.EventLoggingListener: Logging events to hdfs://master:9000/sparklog/application_1469432674658_0001
16/07/25 15:45:25 INFO cluster.YarnClientSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (slave3:53638) with ID 1
16/07/25 15:45:25 INFO cluster.YarnClientSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
16/07/25 15:45:25 INFO storage.BlockManagerMasterEndpoint: Registering block manager slave3:34301 with 853.1 MB RAM, BlockManagerId(1, slave3, 34301)
16/07/25 15:45:25 INFO BwaInterpreter: JMAbuin:: Starting BWA
16/07/25 15:45:25 INFO BwaInterpreter: JMAbuin::Not sorting in HDFS. Timing: 142090691324
16/07/25 15:45:25 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 213.2 KB, free 213.2 KB)
16/07/25 15:45:25 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 19.8 KB, free 233.0 KB)
16/07/25 15:45:25 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on 192.168.100.6:52523 (size: 19.8 KB, free: 853.1 MB)
16/07/25 15:45:25 INFO spark.SparkContext: Created broadcast 0 from newAPIHadoopFile at BwaInterpreter.java:246
16/07/25 15:45:25 INFO storage.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 213.2 KB, free 446.2 KB)
16/07/25 15:45:25 INFO storage.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 19.8 KB, free 466.1 KB)
16/07/25 15:45:25 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on 192.168.100.6:52523 (size: 19.8 KB, free: 853.1 MB)
16/07/25 15:45:25 INFO spark.SparkContext: Created broadcast 1 from newAPIHadoopFile at BwaInterpreter.java:247
16/07/25 15:45:25 INFO input.FileInputFormat: Total input paths to process : 1
16/07/25 15:45:25 INFO input.FileInputFormat: Total input paths to process : 1
16/07/25 15:45:25 INFO rdd.NewHadoopRDD: Removing RDD 0 from persistence list
16/07/25 15:45:25 INFO storage.BlockManager: Removing RDD 0
16/07/25 15:45:25 INFO rdd.NewHadoopRDD: Removing RDD 1 from persistence list
16/07/25 15:45:25 INFO storage.BlockManager: Removing RDD 1
16/07/25 15:45:25 ERROR scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:150)
    at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:150)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:150)
    at org.apache.spark.scheduler.EventLoggingListener.onUnpersistRDD(EventLoggingListener.scala:186)
    at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:50)
    at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
    at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
    at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:55)
    at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:80)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1180)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
Caused by: java.io.IOException: Filesystem closed
    at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:795)
    at org.apache.hadoop.hdfs.DFSOutputStream.flushOrSync(DFSOutputStream.java:1985)
    at org.apache.hadoop.hdfs.DFSOutputStream.hflush(DFSOutputStream.java:1946)
    at org.apache.hadoop.fs.FSDataOutputStream.hflush(FSDataOutputStream.java:130)
    ... 21 more
16/07/25 15:45:25 INFO BwaInterpreter: JMAbuin:: No sort with partitioning
16/07/25 15:45:25 ERROR scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:150)
    at org.apache.spark.scheduler.EventLoggingListener$$anonfun$logEvent$3.apply(EventLoggingListener.scala:150)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.EventLoggingListener.logEvent(EventLoggingListener.scala:150)
    at org.apache.spark.scheduler.EventLoggingListener.onUnpersistRDD(EventLoggingListener.scala:186)
    at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:50)
    at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
    at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
    at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:55)
    at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:80)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1180)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
Caused by: java.io.IOException: Filesystem closed

**Comment by luobailian** [comment]
And not hdfs space is full-----------

Configured Capacity:   58.68 GB 
DFS Used:  3.2 GB 
Non DFS Used:  14.96 GB 
DFS Remaining: 40.52 GB  
DFS Used%: 5.45% 
DFS Rem aining%: 69.05% 
Block Pool Used: 3.2 GB 
Block Pool Used%:  5.45%

**Comment by jmabuin** [comment]
Have you checked if you are able to writ eto HDFS?

Also, can you post your execution command?

**Comment by jmabuin** [comment]
Please, check if it works with SparkBWA 0.2

**Comment by pjongeneel** [comment]
what was the resolution for this?
