### ISSUE TITLE
ERROR YarnScheduler: Lost executor 5 on Mcnode6: remote Rpc client disassociated

### ISSUE THREAD

**Issue by xubo245** [citiususc/SparkBWA#35]
When --executor-cores is  2 ,there are problem:
ERROR YarnScheduler: Lost executor 5 on Mcnode6: remote Rpc client disassociated

SparkBWA-0.1 and SparkBWA-0.2 both.

There are no problem when we set --executor-cores is 1, but CPU utilization of less than 50%  when every node has two core. （through another methods, we can use bwa multithread to improve performance ）

![qq 20170121221430](https://cloud.githubusercontent.com/assets/8759816/22182539/6e499b06-e0e2-11e6-90b9-844e6ff4a261.png)

The error is the same as https://github.com/citiususc/SparkBWA/issues/6

**Comment by jmabuin** [comment]
Can you check the logs and see if any error is reported from this node?

**Comment by xubo245** [comment]
```
SLF4J: Class path contains multiple SLF4J bindings.
16/12/31 12:43:35 INFO yarn.ApplicationMaster: Registered signal handlers for [TERM, HUP, INT]
16/12/31 12:43:36 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1483068084088_1107_000001
16/12/31 12:43:37 INFO spark.SecurityManager: Changing view acls to: hadoop
16/12/31 12:43:37 INFO spark.SecurityManager: Changing modify acls to: hadoop
16/12/31 12:43:38 INFO Remoting: Starting remoting
16/12/31 12:43:38 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkYarnAM@219.219.220.149:57155]
16/12/31 12:43:38 INFO util.Utils: Successfully started service 'sparkYarnAM' on port 57155.
16/12/31 12:43:38 INFO yarn.ApplicationMaster: Waiting for Spark driver to be reachable.
16/12/31 12:43:38 INFO yarn.ApplicationMaster: Driver now available: Master:40715
16/12/31 12:43:38 INFO client.RMProxy: Connecting to ResourceManager at Master/219.219.220.149:8081
16/12/31 12:43:38 INFO yarn.YarnRMClient: Registering the ApplicationMaster
16/12/31 12:43:38 INFO yarn.YarnAllocator: Will request 8 executor containers, each with 2 cores and 7884 MB memory including 716 MB overhead
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.ApplicationMaster: Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals
16/12/31 12:43:38 INFO impl.AMRMClientImpl: Received new token for : Mcnode5:44413
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000003 for on host Mcnode6
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode6
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000004 for on host Mcnode4
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode4
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000005 for on host Mcnode5
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode5
16/12/31 12:43:38 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/12/31 12:43:38 INFO yarn.YarnAllocator: Received 3 containers from YARN, launching executors on 3 of them.
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:38 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Preparing Local resources
SLF4J: Class path contains multiple SLF4J bindings.
16/12/31 12:43:35 INFO yarn.ApplicationMaster: Registered signal handlers for [TERM, HUP, INT]
16/12/31 12:43:36 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1483068084088_1107_000001
16/12/31 12:43:37 INFO spark.SecurityManager: Changing view acls to: hadoop
16/12/31 12:43:37 INFO spark.SecurityManager: Changing modify acls to: hadoop
16/12/31 12:43:38 INFO Remoting: Starting remoting
16/12/31 12:43:38 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkYarnAM@219.219.220.149:57155]
16/12/31 12:43:38 INFO util.Utils: Successfully started service 'sparkYarnAM' on port 57155.
16/12/31 12:43:38 INFO yarn.ApplicationMaster: Waiting for Spark driver to be reachable.
16/12/31 12:43:38 INFO yarn.ApplicationMaster: Driver now available: Master:40715
16/12/31 12:43:38 INFO client.RMProxy: Connecting to ResourceManager at Master/219.219.220.149:8081
16/12/31 12:43:38 INFO yarn.YarnRMClient: Registering the ApplicationMaster
16/12/31 12:43:38 INFO yarn.YarnAllocator: Will request 8 executor containers, each with 2 cores and 7884 MB memory including 716 MB overhead
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:7884, vCores:2>)
16/12/31 12:43:38 INFO yarn.ApplicationMaster: Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals
16/12/31 12:43:38 INFO impl.AMRMClientImpl: Received new token for : Mcnode5:44413
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000003 for on host Mcnode6
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode6
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000004 for on host Mcnode4
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode4
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000005 for on host Mcnode5
16/12/31 12:43:38 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode5
16/12/31 12:43:38 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/12/31 12:43:38 INFO yarn.YarnAllocator: Received 3 containers from YARN, launching executors on 3 of them.
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:38 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Preparing Local resources
16/12/31 12:43:38 INFO yarn.ExecutorRunnable: Preparing Local resources
16/12/31 12:43:39 INFO yarn.ExecutorRunnable:
===============================================================================
YARN executor launch context:
  env:
    SPARK_YARN_CACHE_FILES_FILE_SIZES -> 183993445
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_MODE -> true
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1483159413163
    SPARK_LOG_URL_STDOUT -> http://Mcnode4:8042/node/containerlogs/container_1483068084088_1107_01_000004/hadoop/stdout?start=-4096
    SPARK_YARN_CACHE_FILES -> hdfs://Master:9000/user/hadoop/.sparkStaging/application_1483068084088_1107/spark-assembly-1.5.2-hadoop2.6.0.jar#__spark__.jar

  command:
===============================================================================

16/12/31 12:43:39 INFO yarn.ExecutorRunnable:
===============================================================================
YARN executor launch context:
  env:
    SPARK_LOG_URL_STDERR -> http://Mcnode5:8042/node/containerlogs/container_1483068084088_1107_01_000005/hadoop/stderr?start=-4096
    SPARK_YARN_STAGING_DIR -> .sparkStaging/application_1483068084088_1107
    SPARK_YARN_CACHE_FILES_FILE_SIZES -> 183993445
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_MODE -> true
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1483159413163
    SPARK_LOG_URL_STDOUT -> http://Mcnode5:8042/node/containerlogs/container_1483068084088_1107_01_000005/hadoop/stdout?start=-4096
===============================================================================

16/12/31 12:43:39 INFO yarn.ExecutorRunnable:
===============================================================================
YARN executor launch context:
    SPARK_LOG_URL_STDERR -> http://Mcnode6:8042/node/containerlogs/container_1483068084088_1107_01_000003/hadoop/stderr?start=-4096
    SPARK_YARN_STAGING_DIR -> .sparkStaging/application_1483068084088_1107
    SPARK_YARN_CACHE_FILES_FILE_SIZES -> 183993445
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_MODE -> true
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1483159413163
    SPARK_LOG_URL_STDOUT -> http://Mcnode6:8042/node/containerlogs/container_1483068084088_1107_01_000003/hadoop/stdout?start=-4096
    SPARK_YARN_CACHE_FILES -> hdfs://Master:9000/user/hadoop/.sparkStaging/application_1483068084088_1107/spark-assembly-1.5.2-hadoop2.6.0.jar#__spark__.jar

===============================================================================

16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: Opening proxy : Mcnode5:44413
16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: Opening proxy : Mcnode6:36392
16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: Opening proxy : Mcnode4:60644
16/12/31 12:43:39 INFO impl.AMRMClientImpl: Received new token for : Mcnode3:44832
16/12/31 12:43:39 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000006 for on host Mcnode3
16/12/31 12:43:39 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode3
16/12/31 12:43:39 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000007 for on host Mcnode2
16/12/31 12:43:39 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode2
16/12/31 12:43:39 INFO yarn.YarnAllocator: Launching container container_1483068084088_1107_01_000008 for on host Mcnode7
16/12/31 12:43:39 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler,  executorHostname: Mcnode7
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Preparing Local resources
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Preparing Local resources
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Starting Executor Container
16/12/31 12:43:39 INFO yarn.YarnAllocator: Received 3 containers from YARN, launching executors on 3 of them.
16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/12/31 12:43:39 INFO yarn.ExecutorRunnable: Preparing Local resources
16/12/31 12:43:39 INFO yarn.ExecutorRunnable:
===============================================================================
YARN executor launch context:
  env:
    SPARK_LOG_URL_STDERR -> http://Mcnode7:8042/node/containerlogs/container_1483068084088_1107_01_000008/hadoop/stderr?start=-4096
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_MODE -> true
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1483159413163
    SPARK_LOG_URL_STDOUT -> http://Mcnode7:8042/node/containerlogs/container_1483068084088_1107_01_000008/hadoop/stdout?start=-4096
    SPARK_YARN_CACHE_FILES -> hdfs://Master:9000/user/hadoop/.sparkStaging/application_1483068084088_1107/spark-assembly-1.5.2-hadoop2.6.0.jar#__spark__.jar

  command:
===============================================================================

16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: Opening proxy : Mcnode7:42434
16/12/31 12:43:39 INFO yarn.ExecutorRunnable:
===============================================================================
YARN executor launch context:
  env:
    CLASSPATH -> /home/hadoop/cloud/alluxio-1.3.0/jar/alluxio-1.3.0-spark-client-jar-with-dependencies.jar<CPS>{{PWD}}<CPS>{{PWD}}/__spark__.jar<CPS>$HADOOP_CONF_DIR<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/*<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/lib/*<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/*<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/*<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/lib/*<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*
    SPARK_LOG_URL_STDERR -> http://Mcnode2:8042/node/containerlogs/container_1483068084088_1107_01_000007/hadoop/stderr?start=-4096
    SPARK_YARN_STAGING_DIR -> .sparkStaging/application_1483068084088_1107
    SPARK_YARN_CACHE_FILES_FILE_SIZES -> 183993445
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_MODE -> true
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1483159413163
    SPARK_LOG_URL_STDOUT -> http://Mcnode2:8042/node/containerlogs/container_1483068084088_1107_01_000007/hadoop/stdout?start=-4096
    SPARK_YARN_CACHE_FILES -> hdfs://Master:9000/user/hadoop/.sparkStaging/application_1483068084088_1107/spark-assembly-1.5.2-hadoop2.6.0.jar#__spark__.jar

  command:
    {{JAVA_HOME}}/bin/java -server -XX:OnOutOfMemoryError='kill %p' -Xms7168m -Xmx7168m '-Djava.library.path=/home/hadoop/disk2/xubo/lib' -Djava.io.tmpdir={{PWD}}/tmp '-Dspark.driver.port=40715' -Dspark.yarn.app.container.log.dir=<LOG_DIR> org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler --executor-id 5 --hostname Mcnode2 --cores 2 --app-id application_1483068084088_1107 --user-class-path file:$PWD/__app__.jar 1> <LOG_DIR>/stdout 2> <LOG_DIR>/stderr
===============================================================================

16/12/31 12:43:39 INFO yarn.ExecutorRunnable:
===============================================================================
YARN executor launch context:
  env:
    CLASSPATH -> /home/hadoop/cloud/alluxio-1.3.0/jar/alluxio-1.3.0-spark-client-jar-with-dependencies.jar<CPS>{{PWD}}<CPS>{{PWD}}/__spark__.jar<CPS>$HADOOP_CONF_DIR<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/*<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/lib/*<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/*<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/*<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/*<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/lib/*<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*
    SPARK_LOG_URL_STDERR -> http://Mcnode3:8042/node/containerlogs/container_1483068084088_1107_01_000006/hadoop/stderr?start=-4096
    SPARK_YARN_STAGING_DIR -> .sparkStaging/application_1483068084088_1107
    SPARK_YARN_CACHE_FILES_FILE_SIZES -> 183993445
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_MODE -> true
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1483159413163
    SPARK_LOG_URL_STDOUT -> http://Mcnode3:8042/node/containerlogs/container_1483068084088_1107_01_000006/hadoop/stdout?start=-4096
    SPARK_YARN_CACHE_FILES -> hdfs://Master:9000/user/hadoop/.sparkStaging/application_1483068084088_1107/spark-assembly-1.5.2-hadoop2.6.0.jar#__spark__.jar

  command:
    {{JAVA_HOME}}/bin/java -server -XX:OnOutOfMemoryError='kill %p' -Xms7168m -Xmx7168m '-Djava.library.path=/home/hadoop/disk2/xubo/lib' -Djava.io.tmpdir={{PWD}}/tmp '-Dspark.driver.port=40715' -Dspark.yarn.app.container.log.dir=<LOG_DIR> org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url akka.tcp://sparkDriver@Master:40715/user/CoarseGrainedScheduler --executor-id 4 --hostname Mcnode3 --cores 2 --app-id application_1483068084088_1107 --user-class-path file:$PWD/__app__.jar 1> <LOG_DIR>/stdout 2> <LOG_DIR>/stderr
===============================================================================

16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: Opening proxy : Mcnode3:44832
16/12/31 12:43:39 INFO impl.ContainerManagementProtocolProxy: Opening proxy : Mcnode2:52721
16/12/31 12:48:34 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. Master:40715
16/12/31 12:48:34 INFO yarn.ApplicationMaster: Final app status: SUCCEEDED, exitCode: 0
16/12/31 12:48:34 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with SUCCEEDED
16/12/31 12:48:34 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
16/12/31 12:48:34 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1483068084088_1107
16/12/31 12:48:34 INFO util.ShutdownHookManager: Shutdown hook called
```

**Comment by xubo245** [comment]
```
[main] Version: 0.7.15-r1140
[main] CMD: bwa mem -t 2 /home/hadoop/disk2/xubo/ref/GRCH38L1Index/GRCH38chr1L3556522.fasta /home/hadoop/cloud/workspace/tmps/app-20170213192407-1107-RDD4_1 /home/hadoop/cloud/workspace/tmps/app-20170213192407-1107-RDD4_2
[main] Real time: 2.076 sec; CPU: 16.998 sec
[Java_com_github_sparkbwa_BwaJni_bwa_1jni] Return code from BWA 0.
17/02/13 19:24:28 ERROR BwaAlignmentBase: getOutputFile:/home/hadoop/cloud/workspace/tmps/SparkBWA_g38L100c100000Nhs20Paired1.fastq-18-NoSort-app-20170213192407-1107-4.sam
17/02/13 19:24:28 ERROR BwaAlignmentBase: outputSamFileName:/xubo/project/alignment/sparkBWA/output/g38chr1/standaloneT20170213192403L100c100000Nhs20Paired12/SparkBWA_g38L100c100000Nhs20Paired1.fastq-18-NoSort-app-20170213192407-1107-4.sam
17/02/13 19:24:29 ERROR RetryingBlockFetcher: Exception while beginning fetch of 1 outstanding blocks
java.io.IOException: Failed to connect to Mcnode1/IP:44294
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:193)
        at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:156)
        at org.apache.spark.network.netty.NettyBlockTransferService$$anon$1.createAndStart(NettyBlockTransferService.scala:88)
        at org.apache.spark.network.shuffle.RetryingBlockFetcher.fetchAllOutstanding(RetryingBlockFetcher.java:140)
        at org.apache.spark.network.shuffle.RetryingBlockFetcher.start(RetryingBlockFetcher.java:120)
        at org.apache.spark.network.netty.NettyBlockTransferService.fetchBlocks(NettyBlockTransferService.scala:97)
        at org.apache.spark.storage.ShuffleBlockFetcherIterator.sendRequest(ShuffleBlockFetcherIterator.scala:152)
        at org.apache.spark.storage.ShuffleBlockFetcherIterator.initialize(ShuffleBlockFetcherIterator.scala:265)
        at org.apache.spark.storage.ShuffleBlockFetcherIterator.<init>(ShuffleBlockFetcherIterator.scala:112)
        at org.apache.spark.shuffle.hash.HashShuffleReader.read(HashShuffleReader.scala:43)
        at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala:90)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
        at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:96)
        at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:95)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:29)
        at com.github.sparkbwa.BwaPairedAlignment.call(BwaPairedAlignment.java:94)
        at com.github.sparkbwa.BwaPairedAlignment.call(BwaPairedAlignment.java:33)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction2$1.apply(JavaPairRDD.scala:1024)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:102)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:102)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:727)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$18.apply(RDD.scala:727)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: Mcnode1/IP:44294
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        ... 1 more
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 4601, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (192, 199, 205)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (166, 231)
[M::mem_pestat] mean and std.dev: (198.69, 9.94)
[M::mem_pestat] low and high boundaries for proper pairs: (153, 244)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 10286 reads in 6.262 CPU sec, 4.261 real sec
[main] Version: 0.7.15-r1140
[main] CMD: bwa mem -t 2 /home/hadoop/disk2/xubo/ref/GRCH38L1Index/GRCH38chr1L3556522.fasta /home/hadoop/cloud/workspace/tmps/app-20170213192407-1107-RDD12_1 /home/hadoop/cloud/workspace/tmps/app-20170213192407-1107-RDD12_2
[main] Real time: 4.478 sec; CPU: 20.226 sec
*** Error in `/usr/lib/jvm/jdk1.7.0/bin/java': munmap_chunk(): invalid pointer: 0x00007fc3702d3710 ***

```

**Comment by jmabuin** [comment]
We always executed SparkBWA with JDK 1.8, but I am not sure why you are having an error there, it is very strange

**Comment by xubo245** [comment]
Have you ever run SparkBWA with two core in a executor? (more than one)

There are only one core in a executor  in SparkBWA readme.

I guess:
When more than one core in executor, there maybe a problem in com.github.sparkbwa.BwaPairedAlignment#call.

**Comment by xubo245** [comment]
I will try fix it later.

**Comment by jmabuin** [comment]
Yes, we sometimes have run with 2 or even 4 cores per executor and in each executor several bwa threads

**Comment by xubo245** [comment]
several bwa threads is no problem.

But it is problem when partitions more than the number of  Workers . Did you try this situation?

For example:
-n is a big number

( -n, --partitions <Number of partitions>          Number of partitions to divide input - setPartitionNumber(int))

**Comment by xubo245** [comment]
I have tried many times....

**Comment by xubo245** [comment]
I test  JDK 1.8, it is also error...

**Comment by jmabuin** [comment]
My guess is that,when you have more partitions than number of workers, you are calling the C code several times with JNI.

By doing this, maybe there is some part of the C code that does not contemplate this situation and you are getting an error because of freeing memory that is no allocated or something like that.

My quiestion: why not to set the number of partitions equals to the number of workers? What are you trying to test?

**Comment by xubo245** [comment]
Yes, I try to fix bwa_jni.c by different methods yesterday , but can not fix it.

When set the number of partitions equals to the number of workers, the stage's time equals to the lowest partition run time in all partitions. If uneven data distribution, the stage run time loss 10-15% performance , or more. If can add the number of partitions, it can run faster.

**Comment by xubo245** [comment]
I test SparkBWA in 8 node cluster, there are about 3.2 speedup over BWA-MEM in single node.

Theoretically, we can speedup about 7  or near 8 speedup in 8 node cluster. But SparkBWA has many performance loss , including this and I/O overhead.

**Comment by jmabuin** [comment]
If you have uneven data distribution, try this option and let me know.

spark.shuffle.reduceLocality.enabled=false

**Comment by ghost** [comment]
I am trying to run it on a 4-node cluster (one master and 3 workers) with 125GB memory each and 16 CPU cores. What settings should I be using for memory/partitions/executors? I just can't get it to run successfully. Always crashes with some executor node getting lost (due to memory problem). I have 1TB diskspace on each of the four nodes.

**Comment by jmabuin** [comment]
I would start by try with 10 executors per node and 10 GB per executor, then, if it works, I would try to increase de number of executors and adjust the memory per executor.
