### ISSUE TITLE
Error SparkBWA

### ISSUE THREAD

**Issue by Nav15** [citiususc/SparkBWA#8]
Hello,
 Today I tried to to tun this application with a fresh new Spark-Hadoop cluster but still no luck:

Some logs snippet:

YARN executor launch context:
  env:
    CLASSPATH -> {{PWD}}<CPS>{{PWD}}/**spark**.jar<CPS>$HADOOP_CONF_DIR<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/_<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/lib/_<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/_<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/lib/_<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/_<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/lib/_<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/_<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/_
    **SPARK_YARN_CACHE_ARCHIVES -> hdfs://master:9000/user/hadoop/.sparkStaging/application_1466685575616_0002/bwa.zip#bwa.zip**
    SPARK_LOG_URL_STDERR -> http://client15.example.com:8042/node/containerlogs/container_1466685575616_0002_01_000002/hadoop/stderr?start=-4096
    SPARK_YARN_CACHE_FILES_FILE_SIZES -> 187698038
    SPARK_YARN_STAGING_DIR -> .sparkStaging/application_1466685575616_0002
    SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE
    SPARK_YARN_CACHE_ARCHIVES_FILE_SIZES -> 1001391
    SPARK_USER -> hadoop
    SPARK_YARN_CACHE_ARCHIVES_TIME_STAMPS -> 1466686067853
    SPARK_YARN_MODE -> true
    SPARK_HOME -> /opt/spark/spark-1.6.1-bin-hadoop2.6
    SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1466686067186
    SPARK_LOG_URL_STDOUT -> http://client15.example.com:8042/node/containerlogs/container_1466685575616_0002_01_000002/hadoop/stdout?start=-4096
    SPARK_YARN_CACHE_ARCHIVES_VISIBILITIES -> PRIVATE
    SPARK_YARN_CACHE_FILES -> hdfs://master:9000/user/hadoop/.sparkStaging/application_1466685575616_0002/spark-assembly-1.6.1-hadoop2.6.0.jar#**spark**.jar

 command formed in  application logs :

```
{{JAVA_HOME}}/bin/java -server -XX:OnOutOfMemoryError='kill %p' -Xms1500m -Xmx1500m **'-Djava.library.path=/home/hadoop/LS_Tools/SparkBWA/build/bwa.zip**' -Djava.io.tmpdir={{PWD}}/tmp '-Dspark.driver.port=48908' -Dspark.yarn.app.container.log.dir=<LOG_DIR> -XX:MaxPermSize=256m org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@172.31.32.50:48908 --executor-id 1 --hostname client16.example.com --cores 4 --app-id application_1466685575616_0002 --user-class-path file:$PWD/__app__.jar 1> <LOG_DIR>/stdout 2> <LOG_DIR>/stderr
```

Stack Trace Error:

16/06/23 18:18:36 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-2,5,main]
**java.lang.NoClassDefFoundError: Could not initialize class BwaJni**
    at Bwa.run(Bwa.java:443)
    at BwaRDD$BwaAlignment.call(BwaRDD.java:288)
    at BwaRDD$BwaAlignment.call(BwaRDD.java:173)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
16/06/23 18:18:36 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-3,5,main]
java.lang.NoClassDefFoundError: Could not initialize class BwaJni
    at Bwa.run(Bwa.java:443)
    at BwaRDD$BwaAlignment.call(BwaRDD.java:288)
    at BwaRDD$BwaAlignment.call(BwaRDD.java:173)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
16/06/23 18:18:36 INFO storage.DiskBlockManager: Shutdown hook called
16/06/23 18:18:36 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 36
16/06/23 18:18:36 INFO executor.Executor: Running task 4.0 in stage 3.2 (TID 36)
16/06/23 18:18:36 INFO util.ShutdownHookManager: Shutdown hook called
16/06/23 18:18:36 INFO util.ShutdownHookManager: Deleting directory /home/hadoop/hadoop_tempdir/nm-local-dir/usercache/hadoop/appcache/application_1466685575616_0002/spark-c222af54-6cc2-46f8-b777-8e17e73bef3b
16/06/23 18:18:36 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 37

LogType:stdout
Log Upload Time:23-Jun-2016 18:18:57
LogLength:0
Log Contents:

Command used to run:

**$SPARK_HOME/bin/spark-submit --class SparkBWA --master yarn-client --driver-memory 1500m --executor-memory 1500m --executor-cores 4 --archives bwa.zip --verbose --num-executors 1 SparkBWA.jar -algorithm mem -reads paired -index /Data/HumanBase/ECOLI -partitions 10 ecoli_2.fq ecoli_3.fq ecoli_23_8**

**Comment by Nav15** [comment]
Ran successfully. Please close. thanks
